In [67]:
import pandas as pd

car_dataset = pd.read_csv(r"CARS_1.csv")
car_dataset

,Sr No.,car_name,reviews_count,fuel_type,engine_displacement,no_cylinder,seating_capacity,transmission_type,fuel_tank_capacity,body_type,rating,starting_price,ending_price,max_torque_nm,max_torque_rpm,max_power_bhp,max_power_rp
0,1,Maruti Alto K10,51,Petrol,998,3,5.0,Automatic,27.0,Hatchback,4.5,399000,583000,89.0,3500,65.71,5500
1,2,Maruti Brezza,86,Petrol,1462,4,5.0,Automatic,48.0,SUV,4.5,799000,1396000,136.8,4400,101.65,6000
2,3,Mahindra Thar,242,Diesel,2184,4,4.0,Automatic,57.0,SUV,4.5,1353000,1603000,300.0,2800,130.00,3750
3,4,Mahindra XUV700,313,Diesel,2198,4,7.0,Automatic,60.0,SUV,4.5,1318000,2458000,450.0,2800,182.38,3500
4,5,Mahindra Scorpio-N,107,Diesel,2198,4,7.0,Automatic,57.0,SUV,4.5,1199000,2390000,400.0,2750,172.45,3500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,199,Mercedes-Benz AMG A 45 S,35,Petrol,1991,4,5.0,Automatic,0.0,Hatchback,4.5,659000,999000,500.0,5250,415.71,6750
199,200,BMW 3 Series Gran Limousine,3,Petrol,1998,4,5.0,Automatic,59.0,Sedan,4.5,1041000,1041000,400.0,4400,254.79,5000
200,201,MG Hector Plus,2,Diesel,1956,4,7.0,Manual,60.0,SUV,4.5,1615000,2075000,350.0,2500,167.67,3750
201,202,Audi RS Q8,9,Petrol,3998,8,5.0,Automatic,85.0,SUV,3.5,21700000,21700000,800.0,4500,591.39,6000
202,203,Maruti Alto 800 tour,4,Petrol,796,3,5.0,Manual,35.0,Hatchback,4.5,391000,397000,69.0,3500,47.33,6000

In [ ]:
import pandas as pd

car_dataset = pd.read_csv(r"CARS_1.csv")
car_dataset

car_dataset['fuel_tank_capacity']=car_dataset['fuel_tank_capacity'].astype(dtype={'fuel_tank_capacity': 'string'})
car_dataset['rating']=car_dataset['rating'].astype(dtype={'rating': 'string'})
car_dataset['transmission_type']=car_dataset['transmission_type'].astype(dtype={'transmission_type': 'string'})
car_dataset['reviews_count']=car_dataset['reviews_count'].astype(dtype={'reviews_count': 'string'})
car_dataset['starting_price']=car_dataset['starting_price'].astype(dtype={'starting_price': 'string'})
car_dataset['ending_price']=car_dataset['ending_price'].astype(dtype={'ending_price': 'string'})


car_dataset.isnull().sum()
car_dataset.duplicated().sum()


#car_dataset[['Sr No.','car_name','reviews_count','fuel_type','transmission_type','rating','starting_price','ending_price']]

print("\n\n---------------------------------------<--WELCOME TO CAR RECOMMENDED SYSTEM------>------------------------\n")

def rec_rating():
    a = input("You will get a car based on how many ratings you see?\n")
    new_df=car_dataset[car_dataset['rating'] == a]
    print("\n")
    

    b = input("Which fuel type want you?\n Petrol\n Diesel\n CNG\n Electric\n")
    new_df_Fuel=new_df[new_df['fuel_type'] == b]
    print("\n")
    

    c = input("what is your starting price?\n")
    new_df_starting_price = new_df_Fuel[new_df_Fuel['starting_price'] >= c]
    print("\n")

    e = input("what is your ending price?\n")
    new_df_ending_price = new_df_starting_price[new_df_starting_price['ending_price'] <= e]
    print("\n")


    d = input("what kind transmission type do you want?\n Such as\n Manual\n Electric\n Automatic\n")

    print("See Your Car, which is recommeded according your features:--")

    print(new_df_ending_price[new_df_ending_price['transmission_type'] == d])
    print("\n")

rec_rating()

print("\n\n---------------------------------------<----THANK YOU---\U0001f600--------------->-------------------------\n")

---------------------------------------<--WELCOME TO CAR RECOMMENDED SYSTEM------>------------------------